feat: add avatar click event
decentraland/posix pull request #11
Opened 2021-12-23 19:11 UTC by pbosio

2021-12-23 19:31 UTC, leanmendoza approved these changes

2021-12-23 19:50 UTC, gonpombo8 approved these changes

2021-12-23 19:50 UTC, gonpombo8 commented on src/index.d.ts
> +      direction: number,
remove trailing comma 😄

2021-12-24 13:26 UTC, menduz requested changes

2021-12-24 13:26 UTC, menduz commented on posix.api.md
> +      origin: number
Should origin and direction be vector3?

2021-12-24 13:35 UTC, pbosio commented on posix.api.md
> +      origin: number
🤦‍♂️ Yes! sorry, thanks! fixed :)

2021-12-24 15:26 UTC, menduz approved these changes
:shipit:

2021-12-24 16:50 UTC, menduz commented
One last question before merging: should we include the hit point? If we decide to add it later then it will become optional due to backwards compatibility reasons (first version won't have it)

2021-12-24 17:14 UTC, pbosio commented
> One last question before merging: should we include the hit point? If we decide to add it later then it will become optional due to backwards compatibility reasons (first version won't have it)

I though about that for a while.
We have for input's hit:
```
/** Length of the ray */
length: number
/** If the ray hits a mesh the intersection point will be this */
hitPoint: ReadOnlyVector3
/** If the mesh has a name, it will be assigned to meshName */
meshName: string
/** Normal of the hit */
normal: ReadOnlyVector3
/** Normal of the hit, in world space */
worldNormal: ReadOnlyVector3
/** Hit entity ID if any */
entityId: EntityID
```
For this new event for clicking avatars:
`length` I added as `distance` in the `ray` field
`hitPoint` can be easily calculated with ray's `origin` + `direction` * `distance` 
`meshName` I don't think is really relevant for avatars since it won't be a mesh added by the developer
`normal` and `worldNormal` might be worth adding it but I can only think on super specific use cases 
`entityId` I can't currently think of a good use for that

So I think that for the time being we are exposing the most relevant information and I didn't want to increase the size of the message just because "just in case" :P

2021-12-24 17:34 UTC, merged